# Generated by Django 5.2.10 on 2026-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('file_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('uid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('issuing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
