# Generated by Django 5.2.10 on 2026-01-17 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('ar', 'Arabic'), ('hi', 'Hindi')], max_length=10)),
                ('application_type', models.CharField(choices=[('Employee', 'Employee'), ('Dependent', 'Dependent')], max_length=20)),
                ('dependent_type', models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('', 'N/A')], max_length=20, null=True)),
                ('salary_range', models.CharField(choices=[('<4000', 'Below 4000 AED'), ('4000-5000', '4000-5000 AED'), ('>5000', 'Above 5000 AED')], max_length=20)),
                ('emirates_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('issuing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('issuing_place', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_sponsor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('emirates_id_document', models.FileField(blank=True, null=True, upload_to='emirates_ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Pending OCR', 'Pending OCR'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('LSB', 'Low Salary Bracket'), ('NLSB', 'Non-Low Salary Bracket')], max_length=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='insurance.insuranceapplication')),
            ],
            options={
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
