# Generated by Django 5.2.10 on 2026-01-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceapplication',
            old_name='employer_sponsor_name',
            new_name='sponsor_name',
        ),
    ]
